default_job = "clippy"

[jobs.check]
command = ["cargo", "check", "--workspace", "--color", "always"]
need_stdout = false

[jobs.clippy]
command = ["cargo", "clippy", "--workspace", "--all-features", "--color", "always", "--", "-D", "warnings"]
need_stdout = false

[jobs.test]
command = ["cargo", "nextest", "run", "--workspace", "--color", "always"]
need_stdout = true

[jobs.doc]
command = ["cargo", "doc", "--workspace", "--no-deps", "--color", "always"]
need_stdout = false

[keybindings]
c = "job:check"
l = "job:clippy"
t = "job:test"
d = "job:doc"
