[formatting]
align_entries = false
array_auto_collapse = true
array_auto_expand = true
array_trailing_comma = true
compact_arrays = true
compact_inline_tables = true
indent_string = "    "
reorder_keys = false
trailing_newline = true

[[rule]]
include = ["**/Cargo.toml"]

[[rule]]
include = ["deny.toml", "nextest.toml", "bacon.toml"]

# Exclude vendored/third-party TOML
[[rule]]
exclude = ["tmp/**", "target/**"]
