[package]
name = "mirage-rs"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true
license.workspace = true
authors.workspace = true

[lib]
name = "mirage_rs"
path = "src/lib.rs"
doctest = false

[[bin]]
name = "mirage-rs"
path = "src/main.rs"

[lints]
workspace = true

[dependencies]
anyhow = { workspace = true }
axum = { workspace = true }
alloy-primitives = { workspace = true, features = ["serde"] }
clap = { workspace = true }
futures = { workspace = true }
futures-util = { workspace = true }
golem-core = { path = "../../crates/golem-core" }
jsonrpsee = { workspace = true }
lru = { workspace = true }
dashmap = { workspace = true }
parking_lot = { workspace = true }
reqwest = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
sysinfo = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true }
tokio-tungstenite = { workspace = true }
toml = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
bytes = { workspace = true }
k256 = { workspace = true }
tower = { workspace = true }
tower-http = { workspace = true }

[dev-dependencies]
proptest = { workspace = true }

[features]
default = ["binary"]
binary = []
library = []
sim-gas = []
