[package]
name = "golem-chain"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true
license.workspace = true
authors.workspace = true

[lints]
workspace = true

[dependencies]
alloy = { workspace = true, features = ["rpc-types", "provider-http", "provider-ws", "transport-http", "transport-ws", "signer-local"] }
revm = { workspace = true, features = ["serde"] }
revm-database = "12"
moka = { workspace = true }
tokio = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
uuid = { workspace = true }
thiserror = { workspace = true }
tracing = { workspace = true }
golem-core = { path = "../golem-core" }

[dev-dependencies]
tokio = { workspace = true, features = ["test-util"] }
mirage-rs = { path = "../../apps/mirage-rs", features = ["library"] }
