[book]
title = "Bardo"
description = "Permissionless infrastructure for mortal autonomous agents in DeFi"
authors = ["Bardo Engineering"]
language = "en"
src = "src"

[build]
build-dir = "book"
create-missing = true

[output.html]
site-url = "/"
git-repository-url = "https://github.com/bardo-run/bardo"
edit-url-template = "https://github.com/bardo-run/bardo/edit/main/docs/{path}"

[output.html.search]
enable = false
